[project]
name = "transformations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyproj>=3.7.0",
]

[tool.uv]
dev-dependencies = []
