FROM python:3.11.4-slim-bullseye

RUN apt-get update && \
    apt-get install -y \
        moreutils && \
    pip install --upgrade setuptools

RUN pip install pyproj==3.6.0

# COPY the transformation grids, the modified proj.db and all the other proj files
COPY --from=nsgi/proj:9.2.1 /usr/share/proj/ /usr/local/lib/python3.11/site-packages/pyproj/proj_dir/share/proj/
